Resources:
  UserTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName: '${self:service}-${self:provider.stage}-user-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: providedId
          AttributeType: S
        - AttributeName: provider
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: providedIdGlobalIndex
          KeySchema:
            - AttributeName: providedId
              KeyType: HASH
            - AttributeName: provider
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
